### ISSUE TITLE
Finish the employee side of Cali Panel Developer Preview 1

### ISSUE THREAD

**Issue by NickDerry2023** [NickDerry2023/CaliWebDesignPanel20.0.1#2]
With the release of the Developer Preview 🎉, Cali Web Design is now allowing internal developers to contribute to the panel to bring it closer to the finish line. I am opening this issue to list everything that needs to be done and when one thing is finished on this list I will update this issue checking off the task.

Cali Web Design has been working hard on his panel to bring it to production, we have hired a team of developers to expedite this process.

---

* Dropped Features
* Missing Features
* Disclaimers
* Overall timeline and support

---

### Dropped features that won't make it

These features have been dropped due to technical limitations or the fact vendors don't have existing support for us to tap into.

```
CitiBank Support - Payroll Module - 46093 - CitiBank does not have a public API for us to tie into.
PNCBank Support - Payroll Module - 46093 - PNC does not have a public API for us to tie into.
Okta-based design was scrapped in the alpha release - UI Elements - 98820 - Made the panel UI based on salesforce.
Experian Credit Reporting and Credit Pulling - Financing - 6673920 - Can't obtain the API needed.
TransUnion Credit Reporting and Credit Pulling - Financing - 6673920 - Can't obtain the API needed.
```

---

### Features that are missing

These are features that we have not developed yet that need to be added to the panel

* ~~Employee Management Features.~~
* ~~Website Editing Features.~~
* ~~Missing the ability to deploy new services as a client or as an employee.~~
* ~~Missing Cali Web Design Code Integrity Feature yet the link is present.~~
* ~~The user's online profile management page just is non-existent.~~
* The ability to see online or offline hosts, add new hosts, and control hosts via VMWare ESXi is broken. The panel should see if hosts are available and use any host that has available resources, if a host has less than or at 10GB of ram don't perform the action on that host and pick another, if non-other is available, then make a API call to OVH and request a dedicated server with the plan Advanced 1 with 128GB of RAM and 8TB of Storage.
* The panel is missing the ability to back up services locally or remotely.
* Ability to whitelist or blacklist using the employee side is non-existent.
* The ability for the panel to detect duplicate accounts and match them to existing files to allow the user to log in to just one online or profile doesn't exist.
* The ability to live chat with guests on websites that the panel manages as a business isn't integrated nor can the Cali Web Design Website report live chats to the panel nor can employees message clients from the panel.
* The ability to see and download or upload files to and from Cali Web Design or any other business just doesn't exist.
* Missing the ability to register domains, set hosting plans, and develop APIs as a client using Cali Cloud.
* Missing the ability to view nginx logs of client websites, and clients can't view their own website logs.
* Missing a Web-Based IDE (Integrated Development Environment) - Code Editor.
* VPS Deployment Support.
* Accounting Features and Expense Management.
* Financing and Credit Review.
* ~~Employment Onboarding.~~ (Backend needs to be completed)

---

### Features that are broken

These features are present but aren't working as intended or are missing dependencies or other features that it relies/calls on.

* ~~OAuth for Google, Apple, Discord, Okta, Clever, and Cali OAuth Modules are present but not coded.~~
* ~~Payments for Cali Web Design Merchant Services are in but only on the employee side and it is severely broken~~
* ~~Can't create tasks, link relationships automatically or manually, can't create authorized users or new users as a staff member, can't perform a majority of staff features a company would need on their customers~~.
* ~~Email notices are broken, missing, or non-existent.~~
* ~~When the panel checks IPs it may hang due to calling the API to check IPs too often and causing a rate limit, to solve this if the IP is listed store it in the blacklist file and have it where an employee can remove it.~~
* ~~Dark mode gets stuck if you set it, then refresh the page. (Workaround) - Clear cookies and sign in again.~~
* ~~User Registration and Onboarding aren't finished and Registration is broken as well as Onboarding.~~
* ~~Onboarding is the only thing here that needs finishing.~~
* ~~Panel is not mobile responsive in some places.~~
* ~~The Spanish Language file is not complete, some strings are still in English and the panel does not have a language switcher to switch between languages, or support for more than one language file.~~
* ~~The panel hangs on the loading screen when loading pages if the API is used to check IP address types, and reputation if the API provider throws a rate limit, the panel will either wait for a response or a timeout before loading finishes, and the simple fix is to check IP once then store it in a blacklist if it doesn't pass and require customers to contact us to have it delisted. This would reduce the amount of calls and rate limits.~~
* ~~Employee Management Features and Payroll Module has been started but has no actual logic except for checking the employee's access level and directing them to the right page, employees will be able to see their pay, pay stubs, and anything else such as contracts. Staff will be able to see everything on file about the employee, upload contracts for signing, generate pay forecasts see current pay, and run payroll for a certain employee or all employees. This is a fancy module as it will also file 1099s and W-2s to the IRS and run ACH payments via Chase or Wells Fargo.~~
* ~~Password Reset front end is in but the backend logic doesn't exist.~~
* ~~User Profile edit pages are developed but they are blank only a header bar and checks are present.~~
* Cali Web Design Merchant Services can't issue invoices, view payments (all, specific or risky), missing a bunch of payment features.
* The new email system is in but the ability to compose emails, mark junk, see junk, add emails, or view the system as a client amongst other things is broken and incomplete. The email system also fails to render certain types of emails typically marketing emails but some legitimate ones. This will be worked on.
* Rewrite the IP Checks that the panel does.
* Website Editing Features.
* The verification system to verify customer identities via ID Card, SMS Verification, or Security Questions is either non-existent or severely broken, Twillo does not work so SMS isn't working.
* Cali Web Design Code Integrity Feature is present but is incomplete.
* The panel is using terrible security practices in certain places.

---

There are so many issues with this software. Please feel free to contact me if you want to help contribute or need a list of features I missed in this post. If you find new issues, please feel free to add them as a reply here.

The panel is easier to install now, DB SQL files are not included yet, but the installer script is public and the ENV samples are now included.

---

### Disclaimers

DO NOT RUN THIS PANEL IN A WINDOWS ENVIRONMENT, IT WILL NOT WORK. THE PANEL HAS CORE FUNCTIONS
THAT DEPENDS ON NGINX AND LINUX, THE PANEL DOES NOT USE APACHE.

---

###  Timeline and Support

The foreseeable timeline when this will be released to public testing is within the next 3 -4 months. We don't recommend anyone to install this software until public testing unless you are a developer and are willing to deal with the broken parts or unsupported parts. We will only help internal developers who are actively working on this software as of now.

**Comment by bugsbirb** [comment]
THIS IS CRAZY

**Comment by cloudyio** [comment]
yap god
